# Generated by Django 5.1.2 on 2024-10-14 17:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('highway', 'Highway'), ('street', 'Street'), ('track', 'Track')], default='street', max_length=50)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('description', models.TextField(blank=True, help_text='A brief description of the road')),
            ],
        ),
    ]
