# Generated by Django 5.1.2 on 2024-10-15 13:20

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_road'),
    ]

    operations = [
        migrations.CreateModel(
            name='POIType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('nearest_point_on_road', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('is_public', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, help_text='A brief description of the point of interest')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.road')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.poitype')),
            ],
        ),
    ]
